// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtarLMMwFD-_WOPkioWHeANXHi_hEBHwU',
    appId: '1:786942809012:web:48119c06b9c2b694fc98e1',
    messagingSenderId: '786942809012',
    projectId: 'blood-bank-app-4ca01',
    authDomain: 'blood-bank-app-4ca01.firebaseapp.com',
    databaseURL: 'https://blood-bank-app-4ca01-default-rtdb.firebaseio.com',
    storageBucket: 'blood-bank-app-4ca01.firebasestorage.app',
    measurementId: 'G-7LY35F9G30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRMXoM8lJUuDxDJfd-8eCHkihwl5Kbis',
    appId: '1:786942809012:android:18c85689f431f12cfc98e1',
    messagingSenderId: '786942809012',
    projectId: 'blood-bank-app-4ca01',
    databaseURL: 'https://blood-bank-app-4ca01-default-rtdb.firebaseio.com',
    storageBucket: 'blood-bank-app-4ca01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyK2YpR88GgPpBhY6_2nWpWC8kYR8G4us',
    appId: '1:786942809012:ios:a848dbf6cff74638fc98e1',
    messagingSenderId: '786942809012',
    projectId: 'blood-bank-app-4ca01',
    databaseURL: 'https://blood-bank-app-4ca01-default-rtdb.firebaseio.com',
    storageBucket: 'blood-bank-app-4ca01.firebasestorage.app',
    androidClientId: '786942809012-gls4qlm42g896h5nd0q57atl2jvnp3m2.apps.googleusercontent.com',
    iosClientId: '786942809012-42ibkd9iva8ifbai9tgn33955n7b1gp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyK2YpR88GgPpBhY6_2nWpWC8kYR8G4us',
    appId: '1:786942809012:ios:a848dbf6cff74638fc98e1',
    messagingSenderId: '786942809012',
    projectId: 'blood-bank-app-4ca01',
    databaseURL: 'https://blood-bank-app-4ca01-default-rtdb.firebaseio.com',
    storageBucket: 'blood-bank-app-4ca01.firebasestorage.app',
    androidClientId: '786942809012-gls4qlm42g896h5nd0q57atl2jvnp3m2.apps.googleusercontent.com',
    iosClientId: '786942809012-42ibkd9iva8ifbai9tgn33955n7b1gp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtarLMMwFD-_WOPkioWHeANXHi_hEBHwU',
    appId: '1:786942809012:web:88cc85c698f1ecf6fc98e1',
    messagingSenderId: '786942809012',
    projectId: 'blood-bank-app-4ca01',
    authDomain: 'blood-bank-app-4ca01.firebaseapp.com',
    databaseURL: 'https://blood-bank-app-4ca01-default-rtdb.firebaseio.com',
    storageBucket: 'blood-bank-app-4ca01.firebasestorage.app',
    measurementId: 'G-0BK0Z18XKY',
  );

}